[package]
name = "popup"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5.0"

# macOS native APIs
[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
core-foundation = "0.9"
core-graphics = "0.23"
block = "0.1"
